site_name: Calculations Docs

theme:
  name: "material"

plugins:
  - mkdocstrings
nav:
  - Calculations Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanations.md
